"""updating todo table with created_at and updated_at

Revision ID: 64f05077319c
Revises: 2a97dd1099cd
Create Date: 2026-03-06 10:33:13.770165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f05077319c'
down_revision: Union[str, Sequence[str], None] = '2a97dd1099cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'todos', sa.Column('created_at', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'todos', sa.Column('updated_at', sa.DateTime(), nullable=True)
    )

    op.execute(
        sa.text(
            "UPDATE todos SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP"
        )
    )

    with op.batch_alter_table('todos') as batch_op:
        batch_op.alter_column('created_at', nullable=False)
        batch_op.alter_column('updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###
